# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

variables:
- group: EnglishWordGroup

trigger:
- none

stages:
- stage: CreateAzureResources
  jobs:
  - job: CreateAzureResources
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription(0d01fa01-e307-4b38-b278-cca4bd1ec828)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #create a resource group
          az group create -l $(GROUPLOCATION) -n $(RESOURCEGROUPNAME)

          #create and configure an Azure SQL server
          az sql server create -l $(GROUPLOCATION) -g $(RESOURCEGROUPNAME) -n $(SQLSRVNAME) -u $(SQLUSERNAME) -p $(SQLPASSWORD)
          az sql server firewall-rule create -g $(RESOURCEGROUPNAME) -s $(SQLSRVNAME) -n allowazure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
          
          #create and configure Azure SQL database
          az sql db create -g $(RESOURCEGROUPNAME) -s $(SQLSRVNAME) -n $(DBNAME) --service-objective Basic
          az sql db create -g $(RESOURCEGROUPNAME) -s $(SQLSRVNAME) -n $(DBTESTNAME) --service-objective Basic

          # create and configure an Azure App Service plan and an Azure web app
          az appservice plan create -g $(RESOURCEGROUPNAME) -n $(APIPLANNAME) --l $(APILOCATION) --sku FREE
          az webapp create -g $(RESOURCEGROUPNAME) -p $(APIPLANNAME) -n $(APIAPPNAME)

- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'windows-2022'
    
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    
    steps:
    - task: NuGetToolInstaller@1
    
    - task: UseDotNet@2
      displayName: Use .NET 6.0
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: NuGetCommand@2
      displayName: Restore
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Publish Public API
      inputs:
        command: publish
        publishWebProjects: False
        projects: |
          **/*.csproj 
          !**/*Test.csproj
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/PublicApi'
        zipAfterPublish: False
        modifyOutputPath: False
    
    - task: PowerShell@2
      displayName: 'start mssqllocaldb'
      inputs:
        targetType: 'inline'
        script: 'sqllocaldb start mssqllocaldb'
    
    - task: DotNetCoreCLI@2
      displayName: Run Tests
      inputs:
        command: test
        publishWebProjects: False
        projects: | 
          **/*Test.csproj
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Tests'
        zipAfterPublish: False
        modifyOutputPath: False
    
    - task: FileTransform@1
      displayName: 'File transformation: appsettings.json'
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/PublicApi'
        fileType: 'json'
        targetFiles: |
          **/appsettings.Development.json
          **/appsettings.json
    
    - task: AzureCLI@2
      inputs:
          azureSubscription: 'Visual Studio Professional Subscription(0d01fa01-e307-4b38-b278-cca4bd1ec828)'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # create keys in webapps
            $settings = 
              "ASPNETCORE_ENVIRONMENT=Development"
            
            az webapp config appsettings set -g $(RESOURCEGROUPNAME) -n $(APIAPPNAME) --settings $settings

            az webapp config connection-string set -g $(RESOURCEGROUPNAME) -n $(APIAPPNAME) -t SQLAzure --settings EnglishWordDbConnection='Server=tcp:$(SQLSRVNAME).database.windows.net,1433;Initial Catalog=$(DBNAME);Persist Security Info=False;User ID=$(SQLUSERNAME);Password=$(SQLPASSWORD);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Visual Studio Professional Subscription(0d01fa01-e307-4b38-b278-cca4bd1ec828)'
        appType: 'webApp'
        appName: '$(APIAPPNAME)'
        package: '$(Build.ArtifactStagingDirectory)/PublicApi'
